### PR TITLE
Add support for ARG updates and disable automatic PRs

### PR DESCRIPTION
**Pull request by doitandbedone**
This has been has been fairly manually tested. Could still not figure out how to run/validate test cases however.

This adds support for ARG of formats:

- ARG ARG1="VAL1"
- ARG ARG2

It also adds support to disable automatic PRs via input. Still defaulting to create it however.

### CODE REVIEW

**Comment by doitandbedone** [comment]
Resolved conflicts. I will let you update the README in case you want to run/test changes first. Also, seems there's a problem with config and test can't be run.

**Comment by ludeeus** [comment]
The test issue was fixed in this commit, <https://github.com/ludeeus/dockerfile-updater/commit/af3bbcbfa9541b0d40b5efa47382bd4c3b991902> do a rebase and it should work in your fork as well

**Comment by doitandbedone** [comment]
Just did, thank you!

**Comment by doitandbedone** [comment]
*phew!* Sorry for all the spam, has been quite a learning curve with python/github. But now I feel satisfied and test are all passing. I'll really invest time onto enable local testing for actions.

**Comment by doitandbedone** [comment]
Noticed that in tag 0.2.0, the main Dockerfile got overridden by the test one somehow. I restored the file in this PR. I'd recommend rebuilding 0.2.0.

**Comment by doitandbedone** [comment]
Seems that the imports like to work mutually exclusive from one another, either works for the tests or work for the project. 
The recent change on imports broke building the action when used in workflows but made the test work. But moving them back to how they were breaks tests. Looking into what can be done.

**Comment by ludeeus** [comment]
The testing done is broken, I need to do some restructuring here.
I'll merge this in now and adjust stuff if needed before a new release.
Thanks :+1:

**Pull request merged**
